services:
  backend:
    image: ghcr.io/smashysubash/billsync-backend:latest
    container_name: billsync-backend
    ports:
      - "9001:9001"
    volumes:
      - billsync_uploads:/app/uploads
    environment:
      - MONGO_URI=${MONGO_URI}
      - VENDOR_ZOHO_ID=${VENDOR_ZOHO_ID}
      - UPLOAD_DIR=${UPLOAD_DIR}
    restart: unless-stopped

  frontend:
    image: ghcr.io/smashysubash/billsync-app:latest
    container_name: billsync-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped

volumes:
  billsync_uploads:
