services:
  backend:
    build:
      context: .
    container_name: billsync-backend
    ports:
      - "9001:9001"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: billsync-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
